### ISSUE TITLE
Are the gerber files available

### ISSUE THREAD

**Issue by kb2sdr** [PU2REO/PU2REO_DVFO#1]
Hello,

I noticed you have pictures of the circuit boards for the Arduino and amplifier. Would it be possible to add the gerber files to the repo?

73
Jason
KB2SDR

**Comment by PU2REO** [comment]
Hello and thanks for your message!!

For sure it is!

I'm away from home these days and without my tech gear.

As soon as I get home, will do that!
(Please, drop a message again if you haven't heard of me in a week!! 😜)

73's, REO.

**Comment by PU2REO** [comment]
It's done.

**Comment by kb2sdr** [comment]
Thank you very much!

73
KB2SDR

**Comment by PU2REO** [comment]
if it helped you in some way, please, give me a star: It will encourage me to keep going!
Thanks!
